databases:
 - name: postgres
   ipAllowList: []
   databaseName: nemwel_issue_tracker_production
   user: nemwel_issue_tracker
   plan: free

services:
 - type: web
   name: rails
   env: ruby
   plan: free
   buildCommand: "./bin/render-build.sh"
   startCommand: bundle exec rails s
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: postgres
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false
